### ISSUE TITLE
Errors in other architectures, like ppc64le, s390x or loongarch64

### ISSUE THREAD

**Issue by yjxxin** [mdevctl/mdevctl#105]
When I build mdevctl in other architecture, I found these errors:
![image](https://github.com/mdevctl/mdevctl/assets/35714148/17eb802c-a706-4c20-a5d7-e9ed01f482eb)
What I want to ask is whether this folder `mdevctl-1.1.0/vendor/libc` needs to be replaced, or where do I need to obtain `vendor/libc` for the corresponding architecture?

**Comment by fiuczy** [comment]
I have no problem using `cargo` to build mdevctl on s390x.
Can you provide the commands you are using to get the errors?

**Comment by yjxxin** [comment]
`/usr/bin/env CARGO_HOME=.cargo /usr/bin/cargo build --release -j32`
I was using this command in loongarch64, I wonder if I need to replace the `vendor/libc` folder in this arch

**Comment by fiuczy** [comment]
Running this on s390x works flawless.

```
# /usr/bin/env CARGO_HOME=.cargo /usr/bin/cargo build --release -j32
   Compiling libc v0.2.151
   Compiling version_check v0.9.4
   Compiling proc-macro2 v1.0.70
   Compiling unicode-ident v1.0.12
   Compiling syn v1.0.109
   Compiling unicode-segmentation v1.10.1
   Compiling unicode-width v0.1.11
   Compiling memchr v2.6.4
   Compiling vec_map v0.8.2
   Compiling bitflags v1.3.2
   Compiling ansi_term v0.12.1
   Compiling cfg-if v1.0.0
   Compiling strsim v0.8.0
   Compiling lazy_static v1.4.0
   Compiling rustix v0.38.28
   Compiling serde v1.0.193
   Compiling regex-syntax v0.8.2
   Compiling serde_json v1.0.108
   Compiling hashbrown v0.14.3
   Compiling linux-raw-sys v0.4.12
   Compiling anyhow v1.0.75
   Compiling bitflags v2.4.1
   Compiling equivalent v1.0.1
   Compiling humantime v2.1.0
   Compiling fastrand v2.0.1
   Compiling textwrap v0.11.0
   Compiling log v0.4.20
   Compiling ryu v1.0.16
   Compiling itoa v1.0.10
   Compiling termcolor v1.4.0
   Compiling aho-corasick v1.1.2
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling heck v0.3.3
   Compiling indexmap v2.1.0
   Compiling quote v1.0.33
   Compiling regex-automata v0.4.3
   Compiling atty v0.2.14
   Compiling errno v0.3.8
   Compiling getrandom v0.2.11
   Compiling clap v2.34.0
   Compiling uuid v0.8.2
   Compiling tempfile v3.8.1
   Compiling regex v1.10.2
   Compiling structopt-derive v0.4.18
   Compiling env_logger v0.8.4
   Compiling structopt v0.3.26
   Compiling mdevctl v1.1.0 (/root/devel/test/mdevctl)
    Finished release [optimized] target(s) in 9.08s

```

**Comment by yjxxin** [comment]
Does this mean that the `vendor/libc` folder in this `mdevctl-1.1.0-vendor.tar.gz` is not restricted by the architecture?

**Comment by fiuczy** [comment]
After running the command you gave above I do not have a `mdevctl-1.1.0-vendor.tar.gz` file. Is it possible you are doing something else like e.g. trying to build an rpm or srpm?

**Comment by yjxxin** [comment]
Yes, I am trying to build as srpm, Here is the content of the spec file：
`
%prep
%autosetup -S git_am -n %{name}-%{version}
%cargo_prep -V 1

%build
%cargo_build

 %install
 %make_install

`

**Comment by fiuczy** [comment]
I suggest you start with the provided `mdevctl.spec.in`.

**Comment by yjxxin** [comment]
OK, I will try it, thank you

**Comment by jonner** [comment]
Closing. If you are still having issues, feel free to re-open.
