### ISSUE TITLE
mdev_base affected by MDEVCTL_ENV_ROOT, intended?

### ISSUE THREAD

**Issue by IsaacZD** [mdevctl/mdevctl#120]
I struggled trying to use mdevctl on Nixos. Due to Nixos's limitations I tried use `MDEVCTL_ENV_ROOT` to avoid accessing /usr/lib. However I cannot get any output from `mdevctl types`, and then I figured it's because `$MDEVCTL_ENV_ROOT/sys/bus/mdev/devices` doesn't exist at all. I'm a Linux noob so I could be wrong, but I feel like we should always use `/sys/bus/mdev/devices` instead?

**Comment by jonner** [comment]
This environment variable is not intended for end users, it is only intended for testing.
