### ISSUE TITLE
Device is created even when attribute validation fails

### ISSUE THREAD

**Issue by jonner** [mdevctl/mdevctl#16]
When I attempt to create a device with an invalid attribute, I get an error message and a failure response, but the device still gets created. The code suggests that the device should be removed if attribute validation fails.

```
# mdevctl list
# cat mdev-json-889VI0 
{"mdev_type":"i915-GVTg_V5_8","start":"manual","attrs":[{"invalidattr":"1"}]}
# /usr/sbin/mdevctl start -p 0000:00:02.0 --jsonfile ./mdev-json-889VI0 
Attribute invalidattr cannot be set
[root@himantopus libvirt]# echo $?
1
# mdevctl list
7c6f084a-36a5-41cd-9a5a-eb554413ae85 0000:00:02.0 i915-GVTg_V5_8
```

**Comment by cohuck** [comment]
Can you check whether https://github.com/cohuck/mdevctl/tree/validate works for you?

**Comment by jonner** [comment]
Yes, that seems to fix the issue that I was seeing. 

Using the same json file mentioned above, it still returns a failure status, but doesn't leave under-configured mdev active:

```
# mdevctl start --parent "0000:00:02.0" --jsonfile ./mdev-json-889VI0
Attribute invalidattr cannot be set
# echo $?
1
# mdevctl list
#
```
