### ISSUE TITLE
Use standart path to bash

### ISSUE THREAD

**Issue by shaba** [mdevctl/mdevctl#26]
Fix /usr/bin/bash to /bin/bash in mdevctl shebang.

**Comment by cohuck** [comment]
Is /bin/bash really standard? On newer Linux distros, /bin is a symlink to /usr/bin, and I think /usr/bin/bash is/was the default location on some non-Linux systems.

If /usr/bin/bash is really a problem, using /usr/bin/env would seem like a better solution.

**Comment by shaba** [comment]
mdevctl can be used in distributives with /usr as mount point. Then /usr/bin/env is bad idea.
Distributives with merged /bin and /usr/bin have a symlink /bin -> /usr/bin.
I think use in shebang old style /bin/sh or /bin/bash ise best choice.

**Comment by cpaelzer** [comment]
I thought it is only me/us that are different and [silently changed the path for Debian/Ubuntu](https://sources.debian.org/src/mdevctl/0.61-1/debian/patches/debianize-paths.patch/).
But I agree to @shaba that '/bin/bash' should be the most reliable and common one.
