### ISSUE TITLE
starting a device with parent, type, and uuid options will ignore an existing device config (exists in both bash and rust)

### ISSUE THREAD

**Issue by collinwalling** [mdevctl/mdevctl#38]
When issuing `mdevctl start --parent --type --uuid` in an attempt to start a mediated device with a predefined configuration file with the same UUID, mdevctl will completely ignore the file and quietly create + start a "bare" device. This behavior is present in both the bash and rust versions.

Looking at the man page for the start command:
```
       start DEVICESPEC
           Start  an  mdev  device,  identified by its UUID and optionally its
           parent, or its parent and type and optionally its  UUID,  which  is
           generated if not given.  If specified via its parent and optionally
           its UUID, the type may be specified in a JSON  configuration  file,
           alongside additional parameters.
```
This _does_ say to read the JSON config, specify the parent and optionally a UUID. But does it really make sense to quietly ignore a JSON file if a type is also specified? It may be that at one point, if you had the UUID, type, parent and manual/auto you had everything -- but that's not true for devices with attributes.

In this case, let's say I have a vfio-ap device config that includes attributes at `/etc/mdevctl.d/matrix/2e098a15-e131-4dff-93af-2404eb7e5ddb`:
```
{
  "mdev_type": "vfio_ap-passthrough",
  "start": "auto",
  "attrs": [
    {
      "assign_domain": "0x3b"
    },
    {
      "assign_adapter": "2"
    }
  ]
}
```
If I run `mdevctl start -u 2e098a15-e131-4dff-93af-2404eb7e5ddb`, the JSON file is read in and the device is started as expected.

If I run `mdevctl start -t vfio_ap-passthrough -p matrix -u 2e098a15-e131-4dff-93af-2404eb7e5ddb`, no JSON read is attempted; it's quietly ignored in favor of a new device with no attributes. With debugging enabled (rust version), the following is observed:
```
1         [2021-06-24T19:12:20Z DEBUG mdevctl] Starting up
2         [2021-06-24T19:12:20Z DEBUG mdevctl] DefaultEnvironment { rootpath: "/" }
3         [2021-06-24T19:12:20Z DEBUG mdevctl] Starting device 'Some(2e098a15-e131-4dff-93af-2404eb7e5ddb)'
4         [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Creating mdev 2e098a15-e131-4dff-93af-2404eb7e5ddb
5         [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Loading device '2e098a15-e131-4dff-93af-2404eb7e5ddb' from sysfs
6         [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] loaded device MDev { uuid: 2e098a15-e131-4dff-93af-2404eb7e5ddb, active: false, autostart: false, parent: None, mdev_type: None, attrs: [], env: Environment { \
mdev_base: "/sys/bus/mdev/devices", persist_base: "/etc/mdevctl.d", parent_base: "/sys/class/mdev_bus" } }
7         [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Checking parent for mdev support: "/sys/class/mdev_bus/matrix/mdev_supported_types"
8         [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Checking parent for mdev type vfio_ap-passthrough: "/sys/class/mdev_bus/matrix/mdev_supported_types/vfio_ap-passthrough"
9         [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Checking available instances: "/sys/class/mdev_bus/matrix/mdev_supported_types/vfio_ap-passthrough/available_instances"
10        [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Available instances: 65536
11        [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Creating mediated device: 2e098a15-e131-4dff-93af-2404eb7e5ddb -> "/sys/class/mdev_bus/matrix/mdev_supported_types/vfio_ap-passthrough/create"
12        [2021-06-24T19:12:20Z DEBUG mdevctl::mdev] Setting attributes for mdev 2e098a15-e131-4dff-93af-2404eb7e5ddb
```
Where we can see on line 6, autostart is false (should be true), and the attributes array is empty (should show an adapter and domain). Additionally, a mediated device with this UUID has been quietly created and activated sans attributes -- confirmed by outputting the contents of the device's matrix in sysfs, which shows up empty:
```
# cat /sys/devices/vfio_ap/matrix/2e098a15-e131-4dff-93af-2404eb7e5ddb/matrix 
# 
```
The key thing there being **quietly** -- we finally figured out what was going on by enabling DEBUG on the rust version and noting that it wasn't reading anything from JSON. We can easily rectify this by providing less information on the mdevctl start -- but is there any reason mdevctl ignores a possible JSON file when type and parent are both specified? Shouldn't mdevctl rather read it optionally?  Or at least give some sort of indication that a new device was created VS something from JSON?

While this may be the desirable outcome for attributeless devices, certain devices (such as vfio_ap-passthrough) would benefit from pulling device attributes from an already-defined config file with the same UUID.

**Comment by cohuck** [comment]
Indeed, this looks like unpleasantly surprising behaviour.

I think the desired flow when specifying uuid, parent, and type should be

- Check if we have a JSON file for that combination. If not, create a device and be done.
- Check if the type in the JSON file (if any) matches the one given on the command line. If not, error out.
- Start the device, as specified in the JSON file.

**Comment by jonner** [comment]
> Looking at the man page for the start command:
> 
> ```
>        start DEVICESPEC
>            Start  an  mdev  device,  identified by its UUID and optionally its
>            parent, or its parent and type and optionally its  UUID,  which  is
>            generated if not given.  If specified via its parent and optionally
>            its UUID, the type may be specified in a JSON  configuration  file,
>            alongside additional parameters.
> ```
> 
> This _does_ say to read the JSON config, specify the parent and optionally a UUID. But does it really make sense to quietly ignore a JSON file if a type is also specified? It may be that at one point, if you had the UUID, type, parent and manual/auto you had everything -- but that's not true for devices with attributes.

The way I read this is, it is saying that you can specify additional parameters (i.e. the mdev type and attributes) in a file that you pass as the `--jsonfile` argument. It is not referring to automatically loading a persistent config file definition in `/etc/mdevctl.d`.

However, I agree that it is a bit of a surprising result.

**Comment by collinwalling** [comment]
I agree with Conny's logic above. I wonder if we should also include something on stdout letting the user know if the device was created from scratch, or if a device was created using a config file.

**Comment by cohuck** [comment]
> > Looking at the man page for the start command:
> > ```
> >        start DEVICESPEC
> >            Start  an  mdev  device,  identified by its UUID and optionally its
> >            parent, or its parent and type and optionally its  UUID,  which  is
> >            generated if not given.  If specified via its parent and optionally
> >            its UUID, the type may be specified in a JSON  configuration  file,
> >            alongside additional parameters.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This _does_ say to read the JSON config, specify the parent and optionally a UUID. But does it really make sense to quietly ignore a JSON file if a type is also specified? It may be that at one point, if you had the UUID, type, parent and manual/auto you had everything -- but that's not true for devices with attributes.
> 
> The way I read this is that you can specify additional parameters (i.e. the mdev type and attributes) in a file that you pass as the `--jsonfile` argument. It is not referring to automatically loading a persistent config file definition in `/etc/mdevctl.d`.

Hm. I think the help text needs some clarification, then. We should either explicitly state that the config file needs to be specified via ```--jsonfile```, or go hunting for existing files in the well-known location.

> 
> However, I agree that it is a bit of a surprising result.

**Comment by cohuck** [comment]
> I agree with Conny's logic above. I wonder if we should also include something on stdout letting the user know if the device was created from scratch, or if a device was created using a config file.

I agree, if we support using an existing file, we want to let the user know what was used.

**Comment by jonner** [comment]
@collinwalling does the above patch have the behavior you expect?
