### ISSUE TITLE
Unable to build on RHEL 7.9

### ISSUE THREAD

**Issue by djdejawu** [mdevctl/mdevctl#50]
Greetings.
I am trying to build RPM of this utility for Centos 7.9. The build runs fine, but I get an error when building the RPM.
The utility works correctly, but I would like to create a package for its further implementation into the system by the standard package manager.

```[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
tar -caf target/package/mdevctl-1.1.0-vendor.crate vendor/
rpmbuild -bb --define "_sourcedir /root/mdevctl/target/package" \
        --define "_specdir /root/mdevctl" \
        --define "_builddir /root/mdevctl" \
        --define "_srcrpmdir /root/mdevctl" \
        --define "_rpmdir /root/mdevctl" mdevctl.spec
error:  RPM generation is not yet supported on this distribution
error: Architecture is not included: x86_64
make: *** [rpm] Error 1
```

Please, help.

**Comment by jonner** [comment]
I haven't investigated what it would take to enable the rpm build on centos/rhel 7 or earlier. If anyone would like to submit a patch to enable this, I'd be happy to include it.

**Comment by jamesiter** [comment]
<img width="557" alt="image" src="https://github.com/mdevctl/mdevctl/assets/2541839/230ca897-ad0c-4071-ae66-3bda74ace509">
Just modify there are three places, you'll build rpm of mdevctl successfully.

**Comment by djdejawu** [comment]
oh, it's very kind from you, but It's I have been patched 2 years ago.

**Comment by wnark** [comment]
now need python3-docutils,but centos7 do not have
