### ISSUE TITLE
WARN when script below script.d directly

### ISSUE THREAD

**Issue by smitterl** [mdevctl/mdevctl#52]
I observed the following behavior.

1. Create a script `/etc/mdevctl.d/scripts.d/exit0.sh`
2. Have the script run bash to `exit 0`
3. Run:
```bash
# mdevctl define -t <valid_type> --parent <valid_parent>
cbfa3222-3db3-49f0-a031-52c5f8ecb2e3
# mdevctl start -u cbfa3222-3db3-49f0-a031-52c5f8ecb2e3
```
Result:
```bash
[2021-11-30T14:56:07Z WARN  mdevctl] Can't determine uuid for file 'exit0.sh'
```

I was a bit surprised. I used `script.d` as my "script repository" during script development for testing, that is, create and edit them there before moving them finally to the subfolders.

The action is still executed. But I discussed with @jonner that it could make sense to investigate this.

**Comment by zhuoyingcai** [comment]
Hi Sebastian,
I recalled a similar experience when I was testing the callout scripts. If I remember correctly, mdevctl will treat all files in directories under `/etc/mdevctl.d` as mdev config files, which include files in `/etc/mdevctl.d/scripts.d`. 

You might want to consider ignoring `/etc/mdevctl.d/scripts.d` directory when mdevctl reads through mdev config files or move `/etc/mdevctl.d/scripts.d` directory somewhere else to avoid mdevctl reading any files from it.

Joy
