### ISSUE TITLE
OS error on 'mdevctl list --defined' (no such file or directory)

### ISSUE THREAD

**Issue by otzen** [mdevctl/mdevctl#56]
First please note that I have seen this error from the output of libvirtd, so not 100% sure the error is on mdevctl and not libvirtd.

The error:
```
$ mdevctl list -d
Error: No such file or directory (os error 2)
```
Expected:
```
$ mdevctl list -d
```
If I use the json out format, it maybe becomes more clear.
```
$ mdevctl list --dumpjson -d
Error: No such file or directory (os error 2)
```
Expected:
```
$ mdevctl list --dumpjson -d
[]
```

I might be wrong on this being an error, as I am not familiar with this area, nor this command.
but looking at [mdevctl/tests/list/defined-none.text](https://github.com/mdevctl/mdevctl/blob/master/tests/list/defined-none.text) and  [mdevctl/tests/list/defined-none.json](https://github.com/mdevctl/mdevctl/blob/master/tests/list/defined-none.json) I think I am right in what I expect.

I have no clue what file or folder this command is missing, so if you need more info on this on my system please give information on what to look for. And I will be happy to give info.

My system
```
$ cat /etc/debian_version 
bookworm/sid
$ mdevctl -V
mdevctl 1.1.0
$ /usr/sbin/libvirtd --version
/usr/sbin/libvirtd (libvirt) 7.10.0
```

As mentioned I saw this error from libvirtd log
`jan 02 02:34:46 frink libvirtd[708]: internal error: failed to query mdevs from mdevctl: Error: No such file or directory (os error 2)`

duckduckgo did not find any other reports on this issue, but it did help me track the call to mdevctrl from libvirtd to the function nodeDeviceGetMdevctlListCommand() on line 1060 in [libvirt-7.10.0/src/node_device/node_device_driver.c](https://fossies.org/linux/libvirt/src/node_device/node_device_driver.c) if that is of any help.

**Comment by cohuck** [comment]
Can you check whether /etc/mdevctl.d/ exists? (The rpm spec file takes care of it, not sure how the Debian packaging does it.) I would not expect list -d to look at sysfs if no device had been defined in the first place.

Even if that is the root cause, we'll probably want to error out with a more helpful error message, though.

**Comment by otzen** [comment]
Sorry for the long delay in reply, this transparently slipped my mind.
No /etc/mdevctl.d/ does not exist. No /etc/mdev* dir exsist.

**Comment by otzen** [comment]
I agree that we should get a more informative error message, but as it appears to also be a bug in the deb packaging, i created a bug report on that, you can follow that here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003777

As the maintainer email end in canonical.com I assume this also being an issue on Ubuntu ;-)
