### ISSUE TITLE
`mdevctl` doesn't ignore case sensitivity for `--parent` 

### ISSUE THREAD

**Issue by cdknight** [mdevctl/mdevctl#60]
The `--parent` argument is used to specify a PCI device in the BDF notation. In my case, it's an NVIDIA GPU on ` 0000:2b:00.0`. 

```mdevctl start --uuid `uuidgen` --type nvidia-46 --parent 0000:2b:00.0``` works, but ```mdevctl start --uuid `uuidgen` --type nvidia-46 --parent 0000:2B:00.0``` returns `Error: No available instances of nvidia-46 on 0000:2b:00.0` because `mdevctl` checks for `/sys/bus/pci/devices/<parent>/mdev_supported_types` to be a directory, but the directory represented by `<parent>` is case sensitive (must be lowercase). This nuance in `--parent` is very subtle and difficult to spot, as the BDF numbers are hexadecimal and therefore the chars could be represented in either caps or lowercase.

**Comment by cohuck** [comment]
--parent is supposed to refer to the sysfs entry, which is indeed case sensitive, being a string. For PCI (and others like ccw), the sysfs name is composed of hexadecimal numbers, but it is perfectly legit to have foo and FOO as two different parent devices. So I think we have two issues here:
- The error message is confusing; it needs to match exactly whatever you specified on the command line.
- It seems the documentation is not clear enough: sysfs uses strings, not numbers, and the argument of --parent is a string that needs to match (without parsing.)

**Comment by cdknight** [comment]
At least for PCI, there is no possibility that case sensitivity can refer different devices (as it uses hexadecimal), right? If so, it might be a nice feature that if the device uses hexadecimal, `mdevctl` can ignore case sensitivity (eg. call `.to_lowercase()`) but if not then it preserves case sensitivity?

**Comment by jonner** [comment]
I think it could get a bit fragile to try to decide which strings are safe to lowercase vs those that aren't. Here's a possible idea: don't do any automatic case conversions, but simply look for a directory in sysfs that matches except for case and provide an error message such as:

`Error: Parent device '0000:2B:00.0' not found. Did you mean '0000:2b:00.0'?`

**Comment by cohuck** [comment]
> I think it could get a bit fragile to try to decide which strings are safe to lowercase vs those that aren't.

I agree. We should not make guesses as to how the kernel chooses to represent ids, they should be treated as an opaque handle.

Can we make that more clear in the documentation? It is sometimes hard to figure out which implicit assumptions actually need to be spelled out explicitly.

> Here's a possible idea: don't do any automatic case conversions, but simply look for a directory in sysfs that matches except for case and provide an error message such as:
> 
> `Error: Parent device '0000:2B:00.0' not found. Did you mean '0000:2b:00.0'?`

If that's easy enough to implement, I'm all for it.
