### ISSUE TITLE
offer system-wide equivalent of /etc/mdevctl.d/

### ISSUE THREAD

**Issue by sharkcz** [mdevctl/mdevctl#63]
With the new release the https://github.com/ibm-s390-linux/s390-tools project started to distribute a helper binary `ap-check` that's being installed into `/etc/mdevctl.d/scripts.d/callouts/` (https://github.com/ibm-s390-linux/s390-tools/blob/master/ap_tools/Makefile#L5). It looks wrong to me as this a system-wide binary, but `/etc` is used to local sysadmin-made modification of the system-wide state. Would be right if `mdevctl` had a location for system-wide stuff like `udev` or `systemd` have, something like `/usr/lib/mdevctl/scripts.d/` or so.

**Comment by jonner** [comment]
Sorry for the delayed response. One thing I'm wondering is -- this directory is already used in a released version. It's unfortunate that we didn't think about this before the release. How do you propose dealing with this if we add another location for scripts?

**Comment by jonner** [comment]
I'm not sure I understand what you mean.

**Comment by cohuck** [comment]
Not sure if I'm putting words into @frank-heimes 's mouth, but I think the suggestion is:
- keep `/etc/mdevctl.d/scripts.d/` for scripts (as opposed to binaries); I think that doesn't conflict with the FHS
- add `/usr/lib/mdevctl/scripts.d/` as a place where (scripts and) binaries can go

If we keep the old directories around, I think we should be fine with adding the new location (and making sure that it is the preferable location).
